import { NextResponse } from 'next/server';
import { adminClient } from '@/sanity/lib/adminClient';
import { uploadImagesToSanity, replaceImageUrlsInHtml, getSanityImageUrl } from '@/lib/sanity-image-upload';
import { extractAllImages } from '@/lib/rss-parser';

/**
 * Enhancement endpoint - uploads images to Sanity for existing articles
 * 
 * This runs AFTER sync-articles to upload external images to Sanity CDN
 * Processes ONE article per run
 * Note: HTML content is already generated by sync-articles
 */
export async function GET(request: Request) {
  const isVercelCron = request.headers.get('x-vercel-cron') === '1';
  
  if (!isVercelCron) {
    const cronSecret = process.env.CRON_SECRET;
    if (cronSecret) {
      const authHeader = request.headers.get('authorization');
      const url = new URL(request.url);
      const querySecret = url.searchParams.get('secret');
      
      if (authHeader !== `Bearer ${cronSecret}` && querySecret !== cronSecret) {
        return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
      }
    }
  }

  try {
    console.log('[Enhance] Starting article enhancement...');

    // Find articles with external images (not uploaded to Sanity yet)
    const articlesToEnhance = await adminClient.fetch<
      Array<{
        _id: string;
        title: string;
        description: string;
        content: string;
        contentAr: string;
        htmlContentAr: string;
        imageUrl: string;
        sourceUrl: string;
        image: any;
      }>
    >(
      `*[_type == "article" && 
         imageUrl != null && 
         imageUrl != "" && 
         !defined(image.asset) &&
         !( imageUrl match "cdn.sanity.io*")] | order(_createdAt desc) [0...1] {
        _id,
        title,
        description,
        content,
        contentAr,
        htmlContentAr,
        imageUrl,
        sourceUrl,
        image
      }`
    );

    if (articlesToEnhance.length === 0) {
      return NextResponse.json({
        success: true,
        message: 'No articles need image enhancement (all images uploaded to Sanity)',
        enhanced: 0,
        timestamp: new Date().toISOString(),
      });
    }

    const article = articlesToEnhance[0];
    console.log(`[Enhance] Processing: ${article.title.substring(0, 50)}...`);
    console.log(`[Enhance] Current imageUrl: ${article.imageUrl?.substring(0, 80) || 'none'}...`);

    // Extract images from HTML content (not plain content)
    const htmlContent = article.htmlContentAr || article.contentAr || article.content || '';
    const allImages = extractAllImages(htmlContent, article.sourceUrl);
    const uniqueImages = [...new Set(allImages)];
    
    console.log(`[Enhance] Found ${uniqueImages.length} images in HTML content`);

    // Upload main image if needed
    let sanityImageAssetId: string | null = null;
    if (article.imageUrl && !article.imageUrl.includes('cdn.sanity.io')) {
      console.log(`[Enhance] Uploading main image from: ${article.imageUrl.substring(0, 100)}...`);
      try {
        const imageMap = await uploadImagesToSanity([article.imageUrl]);
        const uploadedAssetId = imageMap.get(article.imageUrl);
        if (uploadedAssetId) {
          sanityImageAssetId = uploadedAssetId;
          console.log(`[Enhance] ✓ Main image uploaded to Sanity: ${uploadedAssetId}`);
        } else {
          console.warn(`[Enhance] ⚠️ Failed to upload main image (no asset ID returned)`);
        }
      } catch (error) {
        console.error(`[Enhance] ✗ Error uploading main image:`, error);
      }
    } else if (!article.imageUrl) {
      console.warn(`[Enhance] ⚠️ No image URL found for article`);
    } else {
      console.log(`[Enhance] ℹ️ Image already in Sanity CDN`);
    }

    // Upload all content images
    let contentImageMap = new Map<string, string>();
    if (uniqueImages.length > 0) {
      console.log(`[Enhance] Uploading ${uniqueImages.length} content images to Sanity...`);
      contentImageMap = await uploadImagesToSanity(uniqueImages);
      console.log(`[Enhance] ✓ Uploaded ${contentImageMap.size} images to Sanity CDN`);
    }

    // Replace image URLs in existing HTML content
    let updatedHtmlContentAr = article.htmlContentAr || article.contentAr || '';
    if (contentImageMap.size > 0 && updatedHtmlContentAr) {
      console.log(`[Enhance] Replacing image URLs in HTML with Sanity CDN URLs...`);
      updatedHtmlContentAr = await replaceImageUrlsInHtml(updatedHtmlContentAr, contentImageMap);
      console.log(`[Enhance] ✓ Replaced ${contentImageMap.size} image URLs`);
    }

    // Update article with enhanced images
    const updateData: any = {};

    // Add updated HTML content with Sanity CDN URLs
    if (updatedHtmlContentAr && updatedHtmlContentAr !== article.htmlContentAr) {
      updateData.htmlContentAr = updatedHtmlContentAr;
      console.log(`[Enhance] ✓ Updated HTML content with Sanity image URLs`);
    }

    // Add image asset if uploaded
    if (sanityImageAssetId) {
      const { urlFor } = await import('@/sanity/lib/image');
      try {
        const sanityImage = {
          asset: {
            _ref: sanityImageAssetId,
            _type: 'reference' as const,
          },
        };
        updateData.image = sanityImage;
        updateData.imageUrl = urlFor(sanityImage).width(1600).height(900).url();
        console.log(`[Enhance] ✓ Updated main image with Sanity CDN URL`);
      } catch {
        updateData.imageUrl = getSanityImageUrl(sanityImageAssetId);
      }
    }

    // Only update if there are changes
    if (Object.keys(updateData).length > 0) {
      await adminClient.patch(article._id).set(updateData).commit();
      console.log(`[Enhance] ✅ Article updated with ${Object.keys(updateData).length} field(s)`);
    } else {
      console.log(`[Enhance] ℹ️ No updates needed`);
    }
    
    console.log(`[Enhance] ✅ Enhanced successfully!`);

    // Count remaining articles with external images
    const remaining = await adminClient.fetch<number>(
      `count(*[_type == "article" && 
              imageUrl != null && 
              imageUrl != "" && 
              !defined(image.asset) &&
              !(imageUrl match "cdn.sanity.io*")])`
    );

    return NextResponse.json({
      success: true,
      message: 'Enhanced 1 article',
      enhanced: 1,
      article: {
        id: article._id,
        title: article.title.substring(0, 60),
      },
      remaining,
      timestamp: new Date().toISOString(),
    });
    
  } catch (error) {
    console.error('[Enhance] Error:', error);
    return NextResponse.json(
      {
        success: false,
        error: 'Enhancement failed',
        message: error instanceof Error ? error.message : 'Unknown error',
        timestamp: new Date().toISOString(),
      },
      { status: 500 }
    );
  }
}

export const POST = GET;

